version: "3.9"
services:
  newrelic:
    image: newrelic/infrastructure:latest
    container_name: newrelic
    privileged: true
    environment:
      NRIA_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NRIA_DISPLAY_NAME: docker-host
    networks:
      - backend

  k6:
    image: grafana/k6
    container_name: k6
    entrypoint: [""]
    command: ["k6", "run", "/scripts/load-test.js"]
    volumes:
      - ./k6-scripts:/scripts
    networks:
      - backend

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    restart: always
    ports:
      - "8082:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    depends_on:
      - kafka
    networks:
      - backend
      - management
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kafka-ui.rule=Host(`kafka.mydomain.com`)"
      - "traefik.http.routers.kafka-ui.entrypoints=websecure"
      - "traefik.http.routers.kafka-ui.tls=true"
      - "traefik.http.services.kafka-ui.loadbalancer.server.port=8080"
      - "traefik.http.routers.kafka-ui.middlewares=security-headers@file,cors@file"

networks:
  backend:
    external: true
  management:
    external: true
