version: "3.9"
services:
  newrelic:
    image: newrelic/infrastructure:latest
    container_name: newrelic
    privileged: true
    environment:
      NRIA_LICENSE_KEY: ${NEW_RELIC_LICENSE_KEY}
      NRIA_DISPLAY_NAME: docker-host
    networks:
      - backend

  k6:
    image: grafana/k6
    container_name: k6
    entrypoint: [""]
    command: ["k6", "run", "/scripts/load-test.js"]
    volumes:
      - ./k6-scripts:/scripts
    networks:
      - backend

networks:
  backend:
    external: true