version: "3.9"
services:
  spring-app:
    image: "${DOCKER_USER_NAME}/${DOCKER_IMAGE_NAME}:latest"
    container_name: spring-app
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./config/spring-app.env
    depends_on:
      - postgres
      - redis
    networks:
      - backend
      - frontend

networks:
  backend:
    external: true
  frontend:
    external: true