version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    env_file:
      - ./config/postgres-secret.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7
    container_name: redis
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  backend:
    external: true